# Generated by Django 5.0.4 on 2024-05-25 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dryWashing",
            "0002_clothes_alter_user_options_remove_user_custom_groups_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="pickup_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="deposit_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
