# Generated by Django 5.0.4 on 2024-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dryWashing", "0003_blacklistedtoken_cartitem_pickup_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
