# Generated by Django 5.0.4 on 2024-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dryWashing", "0004_alter_blacklistedtoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothes",
            name="image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="uploads/clothes/"
            ),
            preserve_default=False,
        ),
    ]
