# Generated by Django 5.0.4 on 2024-06-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryWashing', '0005_clothes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'clothes'},
        ),
    ]
