# Generated by Django 5.0.4 on 2024-08-10 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dryWashing", "0006_alter_clothes_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="Clothes",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="client",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
