# Generated by Django 5.0.4 on 2024-11-22 15:39

import django.db.models.deletion
import dryWashing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryWashing', '0007_remove_cartitem_clothes_remove_cartitem_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=dryWashing.models.User)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('codePostal', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dryWashing.user')),
            ],
        ),
    ]
