# Generated by Django 5.0.4 on 2025-01-31 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_order_order_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_item",
            old_name="prix",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="quantite",
            new_name="quantity",
        ),
    ]
