# Generated by Django 5.0.4 on 2025-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_rename_prix_order_item_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
