# Generated by Django 5.0.4 on 2025-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_order_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_delivered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
