# Generated by Django 5.0.4 on 2025-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_order_date_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("LINGE_RECU", "Linge reçu"),
                    ("EN_COURS", "En cours de nettoyage"),
                    ("PRET_A_LIVRER", "Prêt à livrer"),
                ],
                default="LINGE_RECU",
                max_length=20,
            ),
        ),
    ]
