# Generated by Django 5.0.4 on 2024-08-10 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dryWashing", "0007_remove_cartitem_clothes_remove_cartitem_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pickup_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "Clothes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dryWashing.clothes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dryWashing.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_checked_out", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dryWashing.user",
                    ),
                ),
                ("items", models.ManyToManyField(to="cart.cartitem")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SALE", "Linge sale"),
                            ("EN COURS DE TRAITEMENT", "linge en cours de traitement"),
                            ("PROPRE", "Linge propre"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dryWashing.user",
                    ),
                ),
            ],
        ),
    ]
